version: '3.8'

services:
  # มีแค่ Next.js Application ตัวเดียวพอ เพราะ DB อยู่ที่ Supabase แล้ว
  app:
    image: ghcr.io/taichi112/personal-profile-app:latest  # 👈 [เพิ่มใหม่] ชี้ไปที่โกดัง GHCR ของคุณ
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     NODE_ENV: production
    container_name: personal-profile-app-prod
    restart: always
    environment:
      # ให้มันอ่านค่า DATABASE_URL จากไฟล์ .env โดยตรง
      DATABASE_URL: ${DATABASE_URL}

      # Next.js
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}

      # NextAuth
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}

      # Auth Providers (ถ้ามี)
      GITHUB_ID: ${GITHUB_ID}
      GITHUB_SECRET: ${GITHUB_SECRET}
      GOOGLE_ID: ${GOOGLE_ID}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
      # สังเกตว่าเรา 'comment' ports ออกไปแล้ว เพราะเราจะไม่ให้แขกเข้าแอปตรงๆ
      # ports:
      # - "${APP_PORT:-3000}:3000"
    networks:
      - app-network-prod
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 512M
  # Nginx Reverse Proxy (ยามหน้าประตู)
  nginx:
    image: nginx:alpine
    container_name: personal-profile-nginx
    restart: always
    ports:
      - "80:80" # รับแขกทางประตู 80
      - "443:443" # เตรียมไว้สำหรับเฟส 2 (HTTPS)
    volumes:
      # เอาไฟล์ตั้งค่าที่เราเขียนไปสวมทับค่าเริ่มต้นของ Nginx
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt    # [เพิ่ม] โฟลเดอร์รับกุญแจ
      - ./certbot/www:/var/www/certbot     # [เพิ่ม] โฟลเดอร์ยืนยันตัวตน
    depends_on:
      - app
    networks:
      - app-network-prod

  # [เพิ่มใหม่ทั้งก้อน] หุ่นยนต์ขอใบรับรอง
  certbot:
    image: certbot/certbot
    container_name: personal-profile-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

networks:
  app-network-prod:
    driver: bridge
