# nginx/nginx.conf

server {
    listen 80;
    server_name taichi112.works www.taichi112.works;

    # 1. เปิดช่องทางลับให้หน่วยงาน Let's Encrypt เข้ามาตรวจบัตร
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    
    location / {
        # ส่งแขก (Request) ไปหาคอนเทนเนอร์ที่ชื่อ 'app' ที่พอร์ต 3000
        proxy_pass http://app:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        
        # ส่ง IP จริงของแขกเข้าไปให้แอป Next.js รู้จักด้วย
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}